//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimateEquipment.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Job_title { get; set; }
        public int BidID { get; set; }
    
        public virtual Bid Bid { get; set; }
    }
}
